---
title: "BD Organic vs. Whole Liver"
author: "Emily Wolfrum"
date: "2024-06-18"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)


```

```{r}

pacman::p_load(tidyverse, pheatmap, ggVennDiagram, patchwork, ggrepel, ordinal, factoextra, data.table, limma, clusterProfiler, org.Mm.eg.db, readxl, ggforce)  

krange <- c("#ced3df", "#b5bdcf", "#9ba8c0", "#8192af", "#697e9f", "#506890", "#36507f", "#1f3970", "#04235e")

my_pal = c("#ced3df","#8192af","#1f3970" )

my_pal =c("#ced3df","#ea8d55","#008000","black")

col.whole.liver = c("#d4d4d3") 


```

## intersection = pathway enriched 

## universe = union of liver + bd_organic 

```{r}

liver = read.table("Fig2_E_Kobold_44200NF_44200F_44250NF_44250F_Whole_Report.tsv", sep = "\t", quote = "") 

bdaq = read.table("Fig2_C_Kobold_44200_BDaq_BDorg_80MeOH_Report.tsv", sep = "\t", quote = "") 

colnames(bdaq) <- bdaq[1, ]
bdaq = bdaq[-1, ]

colnames(bdaq) <- gsub("PC00033_Project|PG.Quantity|.raw.", "", colnames(bdaq))

colnames(liver) <- liver[1, ]
liver = liver[-1, ]

colnames(liver) <- gsub("PC00033_Project|PG.Quantity|.raw.", "", colnames(liver))


bdaq.all = bdaq 
liver.all = liver

```



```{r}

## select only bd_organic columns as well as columns containing protein description info  

bdaq = bdaq %>% 
  dplyr::select(c(1:6), contains("BD_Organic"))

## select only whole liver columns as well as columns containing protein description info  
liver = liver %>% dplyr::select(c(1:6), contains("Liver")) 

```

## all possible proteins from either liver or BD Organic 

```{r}

char.vector = "BD AQ vs. Whole Liver"

### need the sheet that corresponds to the bd_organic experiment: 
whole = read_excel("proteins in metabolite extracts (1).xlsx", sheet=2)

genes = unique(bdaq$PG.Genes) 

### find enriched using genes as key 
enrich.all.3 = unlist(mapIds(org.Mm.eg.db, keys = genes,
       column = "ENTREZID", keytype = "SYMBOL"))

genes.univ = unique(bdaq$PG.Genes) 

enrich.univ = unlist(mapIds(org.Mm.eg.db, keys = union(unlist(liver$PG.Genes), genes.univ),
       column = "ENTREZID", keytype = "SYMBOL"))

## 
paths = as.data.frame(enrichGO(enrich.all.3,'org.Mm.eg.db',ont="BP",universe = enrich.univ))

paths$GeneRatio = sapply(paths$GeneRatio , function(x) eval(parse(text = x)))

paths$qvalue = -log10(paths$qvalue)
paths$label = paths$Description

paths$label[11:nrow(paths)]=""

## plot gsea:
p = ggplot(paths,aes(x =GeneRatio,y=qvalue ,size=qvalue,fill=GeneRatio)) +
  geom_point(shape=21) +
  theme_bw()  +
  geom_text_repel(aes(label = label), size=3,  max.overlaps = Inf, nudge_x = 0.05, #label.padding = .2,
box.padding = 2.25,color="black", direction = "y") +
  scale_fill_gradient(low="white",high="red") +
  labs(title = char.vector) +
   scale_x_continuous(expand = expansion(mult = .3))

```

## intersection = pathway enriched 

## universe = union of liver + bd_organic 


```{r}

whole = read_excel("proteins in metabolite extracts (1).xlsx", col_names = FALSE, sheet=2)
colnames(whole) <- c("genes") 

char.vector = c("BD Organic vs. Whole Liver")
### this used to be the genes unique to the res1 object 
genes = bdaq$PG.Genes
liver.genes = liver$PG.Genes
whole.genes = whole$genes


enrich.all.3 = unlist(mapIds(org.Mm.eg.db, keys = genes,
       column = "ENTREZID", keytype = "SYMBOL"))

enrich.univ = unlist(mapIds(org.Mm.eg.db, keys = union(union(unlist(whole.genes), liver.genes), genes), 
       column = "ENTREZID", keytype = "SYMBOL"))

paths = as.data.frame(enrichGO(enrich.all.3,'org.Mm.eg.db',ont="BP",universe = enrich.univ, pvalueCutoff = 0.99)) ## RESUBMIT FORMATTING; REMOVE FILTER FOR P-VALS

paths$GeneRatio = sapply(paths$GeneRatio , function(x) eval(parse(text = x)))
paths$significant = ifelse(paths$qvalue < 0.05, "Significant", "NS")
paths$qvalue = -log10(paths$qvalue)
paths$label = paths$Description 
paths$label[11:nrow(paths)]=""

#label.padding = .2
p = ggplot(paths,aes(x =GeneRatio, y=qvalue , color=significant)) + 
  geom_point(size = 3) +
  theme_bw()  +
  geom_text_repel(aes(label = label), size=4,  max.overlaps = Inf, nudge_x = 0.05, 
box.padding = 2.25,color="red", direction = "y") + 
  scale_color_manual(values = c("black", "red")) + 
  labs(title = char.vector) + 
   scale_x_continuous(expand = expansion(mult = .3)) 

p

### USE EXPORT GUI TO MAKE PDF 4 X 6 " 



```




